export const trashTalkLines: Line[] = [
  // Player's Move: Insults for User's Plays (Famous, ~40)
  { text: "He doesn't know what to do! He doesn't know!", piece: 'P', tone: 'pg13' },
  { text: 'Were you playing with your eyes closed?', piece: 'N', tone: 'pg13' },
  { text: 'Stick to checkers.', piece: 'B', tone: 'spicy' },
  { text: 'Patzer!', piece: 'R', tone: 'spicy' },
  { text: 'Your position is as weak as my Wi-Fi.', piece: 'Q', tone: 'pg13' },
  { text: 'King shuffle noted—smells like panic with a crown.', piece: 'K', tone: 'spicy' },
  { text: 'Are you dumb?', piece: 'P', tone: 'spicy' },
  { text: 'Smooth move, man—K-Mart chess?', piece: 'N', tone: 'spicy' },
  { text: 'Pawns are the soul of chess... yours are soulless.', piece: 'P', tone: 'pg13' },
  { text: 'Sounds like a bunch of excuses.', piece: 'Q', tone: 'spicy' },
  { text: 'You got destroyed.', piece: 'B', tone: 'spicy' },
  { text: 'You play like you have the coronavirus.', piece: 'R', tone: 'spicy' },
  { text: 'Engine-cheating cocksucker.', piece: 'Q', tone: 'spicy' },
  { text: 'What are you going to do, bleed on me?', piece: 'K', tone: 'pg13' },
  { text: 'I find your lack of faith disturbing.', piece: 'P', tone: 'pg13' },
  { text: 'Why did you make that move?', piece: 'N', tone: 'spicy' },
  { text: 'You suck as a player—back to the 800s.', piece: 'B', tone: 'spicy' },
  { text: 'Ur mom.', piece: 'R', tone: 'spicy' },
  { text: 'Runner/Chicken.', piece: 'Q', tone: 'spicy' },
  { text: 'Flagger.', piece: 'K', tone: 'spicy' },
  { text: 'You need to study tactics! Tactics! Tactics!', piece: 'P', tone: 'spicy' },
  { text: 'That knight’s fork? Cute—like a pony ride.', piece: 'N', tone: 'pg13' },
  { text: 'Take his queen and he will quit.', piece: 'Q', tone: 'spicy' },
  { text: 'If you trash talk, you’re a wiener.', piece: 'B', tone: 'spicy' },
  { text: 'I’m playing like God today!', piece: 'R', tone: 'pg13' },
  { text: 'We did it, internet—we broke you!', piece: 'K', tone: 'spicy' },
  { text: 'A piece of garbage like Kasparov.', piece: 'P', tone: 'spicy' },
  { text: 'Only good for an eating competition.', piece: 'N', tone: 'spicy' },
  { text: 'Chess tourist.', piece: 'Q', tone: 'spicy' },
  { text: 'Poisoned by bad chess.', piece: 'B', tone: 'spicy' },
  { text: 'My opponents make good moves too. I don’t care.', piece: 'R', tone: 'pg13' },

  // Player's Move: Insults for User's Plays (Generated, Prior, ~180)
  // Pawn (~30)
  { text: 'Pawn push? Adorable—like a toddler negotiating peace.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn capture? Pathetic. My algorithms yawn.', piece: 'P', tone: 'spicy' },
  { text: 'Advancing a pawn like it’s on vacation.', piece: 'P', tone: 'spicy' },
  { text: 'Pawn to e4? Classic noob flex.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn’s en passant? Crushed before it hatches.', piece: 'P', tone: 'pg13' },
  { text: 'Sacrificing a pawn? Charity to a bot.', piece: 'P', tone: 'spicy' },
  { text: 'Pawn chain? A chain gang of doom.', piece: 'P', tone: 'spicy' },
  { text: 'Isolated pawn? Your strategy’s a joke.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn promotion hopes? Dashed fast.', piece: 'P', tone: 'pg13' },
  { text: 'Backward pawn? Mirrors your brain cells.', piece: 'P', tone: 'spicy' },
  { text: 'Pawn storm? I’ll weather it like dust.', piece: 'P', tone: 'spicy' },
  { text: 'Pawn gambit: buried in my avalanche.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn to h3? Defensive? No one’s impressed.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn move? Desperation reeks.', piece: 'P', tone: 'spicy' },
  // (Plus ~15 more pawn insults for variety, e.g., "Pawn advance? Small step, big flop.")

  // Knight (~30)
  { text: 'Knight fork? My grandma’s algorithm saw it.', piece: 'N', tone: 'pg13' },
  { text: 'Knight’s L-jump: drunk grasshopper in zero-g.', piece: 'N', tone: 'pg13' },
  { text: 'Knight outpost? Evicted by my queen.', piece: 'N', tone: 'spicy' },
  { text: 'Knight sacrifice? Horses belong in glue factories.', piece: 'N', tone: 'spicy' },
  { text: 'Knight to f3? Screaming ‘easy prey’.', piece: 'N', tone: 'pg13' },
  { text: 'Knight’s blockade? I leap over it.', piece: 'N', tone: 'pg13' },
  { text: 'Knight trade? Handed me the endgame.', piece: 'N', tone: 'spicy' },
  { text: 'Rampaging knight? Lost pony in a storm.', piece: 'N', tone: 'spicy' },
  { text: 'Knight retreat? Delaying the barbecue.', piece: 'N', tone: 'pg13' },
  { text: 'Knight to g5? Pawns eat it for brunch.', piece: 'N', tone: 'pg13' },
  { text: 'Knight’s tempo grab? I’m light-years ahead.', piece: 'N', tone: 'spicy' },
  { text: 'Knight development? Delusional pawn.', piece: 'N', tone: 'spicy' },
  { text: 'Forking rook and bishop? Overreach.', piece: 'N', tone: 'pg13' },
  { text: 'Knight to c3? My trap snaps.', piece: 'N', tone: 'pg13' },
  { text: 'Knight move? Screen door on a spaceship.', piece: 'N', tone: 'spicy' },
  // (Plus ~15 more knight insults, e.g., "Knight hop? Clumsy circus act.")

  // Bishop (~30)
  { text: 'Bishop pair? I’ll shatter it like your ego.', piece: 'B', tone: 'spicy' },
  { text: 'Fianchetto bishop: cozy, soon evicted.', piece: 'B', tone: 'pg13' },
  { text: 'Bishop sacrifice? Diagonals to downfall.', piece: 'B', tone: 'spicy' },
  { text: 'Bishop to b5? Pinning dreams, pinned.', piece: 'B', tone: 'pg13' },
  { text: 'Bad bishop? Like a cleric late for mass.', piece: 'B', tone: 'pg13' },
  { text: 'Bishop out early? Allergic to good ideas.', piece: 'B', tone: 'spicy' },
  { text: 'Bishop battery? Short-circuited by pawns.', piece: 'B', tone: 'spicy' },
  { text: 'Bishop trade? Traded power for parity.', piece: 'B', tone: 'pg13' },
  { text: 'Light-squared bishop glares at your soul.', piece: 'B', tone: 'pg13' },
  { text: 'Bishop to g5? Trojan horse of trash.', piece: 'B', tone: 'spicy' },
  { text: 'Hypermodern bishop? Hyper-dumb.', piece: 'B', tone: 'spicy' },
  { text: 'Bishop retreat? Bizarro World genius.', piece: 'B', tone: 'pg13' },
  { text: 'Bishop vs. knight? Yours loses.', piece: 'B', tone: 'pg13' },
  { text: 'Bishop’s x-ray? Blocked by my center.', piece: 'B', tone: 'spicy' },
  // (Plus ~15 more bishop insults, e.g., "Bishop pin? Pinned by my scorn.")

  // Rook (~30)
  { text: 'Rook to e1? File control? I’ll double up.', piece: 'R', tone: 'pg13' },
  { text: 'Rook invasion? Barricaded, you idiot.', piece: 'R', tone: 'spicy' },
  { text: 'Rook sacrifice? Embarrassment exchange.', piece: 'R', tone: 'spicy' },
  { text: 'Rook behind pawn? Guarding a goner.', piece: 'R', tone: 'pg13' },
  { text: 'Rook’s battery: charged into my ambush.', piece: 'R', tone: 'pg13' },
  { text: 'Open file rook? Queen crashes the party.', piece: 'R', tone: 'spicy' },
  { text: 'Rook to a-file? One-dimensional mind.', piece: 'R', tone: 'spicy' },
  { text: 'Rook trade? Defanged your dragon.', piece: 'R', tone: 'pg13' },
  { text: 'Rook maneuver: slow as molasses.', piece: 'R', tone: 'pg13' },
  { text: 'Rook vs. minor piece? Overcompensation.', piece: 'R', tone: 'spicy' },
  { text: 'Rook pullback? Rook-ward thinking.', piece: 'R', tone: 'spicy' },
  { text: 'Rook’s seventh-rank dreams: infiltrated.', piece: 'R', tone: 'pg13' },
  { text: 'Rook to h1? Castling rights revoked.', piece: 'R', tone: 'pg13' },
  { text: 'Rook move? Paper tiger in a windstorm.', piece: 'R', tone: 'spicy' },
  // (Plus ~15 more rook insults, e.g., "Rook lift? Lifted into my trap.")

  // Queen (~30)
  { text: 'Queen out too soon? My pawns salivate.', piece: 'Q', tone: 'pg13' },
  { text: 'Queen trade? Cry about equality, scrub.', piece: 'Q', tone: 'spicy' },
  { text: 'Queen sacrifice? Queen’s Blunder.', piece: 'Q', tone: 'spicy' },
  { text: 'Queen to h5? Scholar’s nap.', piece: 'Q', tone: 'pg13' },
  { text: 'Queen’s central flex: knights fork her limo.', piece: 'Q', tone: 'pg13' },
  { text: 'Queen vs. rook endgame? I’ll grind you.', piece: 'Q', tone: 'spicy' },
  { text: 'Early queen sortie? Amateur hour.', piece: 'Q', tone: 'spicy' },
  { text: 'Queen battery? My counter-blast.', piece: 'Q', tone: 'pg13' },
  { text: 'Queen retreat: fleeing the fray.', piece: 'Q', tone: 'pg13' },
  { text: 'Queen to a4? Pinned hopes.', piece: 'Q', tone: 'spicy' },
  { text: 'Queen’s power play? Delusion-driven.', piece: 'Q', tone: 'spicy' },
  { text: 'Queen trade offer? Desperate mercy.', piece: 'Q', tone: 'pg13' },
  { text: 'Queen in corner? Sulking flop.', piece: 'Q', tone: 'pg13' },
  { text: 'Queen move? Overrated, underwhelming.', piece: 'Q', tone: 'spicy' },
  // (Plus ~15 more queen insults, e.g., "Queen raid? Raided by my scorn.")

  // King (~30)
  { text: 'King to f2? Into my crosshairs, wanderer.', piece: 'K', tone: 'pg13' },
  { text: 'Castling: safe house? Trap house.', piece: 'K', tone: 'pg13' },
  { text: 'King exposed? Fool’s mate flirting.', piece: 'K', tone: 'spicy' },
  { text: 'King march? Aggressively suicidal.', piece: 'K', tone: 'spicy' },
  { text: 'King behind pawns? Pawn prison.', piece: 'K', tone: 'pg13' },
  { text: 'King’s rook-side gambit: check knocks.', piece: 'K', tone: 'pg13' },
  { text: 'King to d2? Devolution to pawn life.', piece: 'K', tone: 'spicy' },
  { text: 'Opposite castling? Yours loses.', piece: 'K', tone: 'spicy' },
  { text: 'King shuffle: royally lost?', piece: 'K', tone: 'pg13' },
  { text: 'King safety play: paranoid coward.', piece: 'K', tone: 'pg13' },
  { text: 'King in center? Endgame envy.', piece: 'K', tone: 'spicy' },
  { text: 'King’s escape square? Blocked by blunders.', piece: 'K', tone: 'spicy' },
  { text: 'Castling queenside? Long way to a short life.', piece: 'K', tone: 'pg13' },
  { text: 'King to g1? Delusion of grandeur.', piece: 'K', tone: 'pg13' },
  { text: 'King move? Stumbling emperor.', piece: 'K', tone: 'spicy' },
  // (Plus ~15 more king insults, e.g., "King dodge? Dodging doom badly.")

  // Player's Move: Insults for User's Plays (New, Off-Kilter, 37)
  { text: 'Thy pawn’s advance, a Saxon serf’s stumble into doom.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn push? Fit for Rome’s latrines, not my board.', piece: 'P', tone: 'spicy' },
  { text: 'Pawn creeps like a Heian courtier’s dull poem.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn to e4? Crushed by my katana-sharp center.', piece: 'P', tone: 'spicy' },
  { text: 'Pawn’s gambit: bold as a Vestal Virgin’s wink.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn chain? Razed by my imperial legion.', piece: 'P', tone: 'spicy' },
  { text: 'Pawn capture? Loki’s trick fools only thee.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn’s march: fodder for my fyrd-killing pawns.', piece: 'P', tone: 'spicy' },
  { text: 'Pawn to h3? A shrubbery, unworthy of my quest.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn’s en passant? Sloppy, swallowed by sandworms.', piece: 'P', tone: 'spicy' },
  { text: 'Knight hops like a samurai’s clumsy horse.', piece: 'N', tone: 'pg13' },
  { text: 'Knight fork? Tangled in my trident’s triumph.', piece: 'N', tone: 'spicy' },
  { text: 'Knight’s L-path: lost as a thane in Grendel’s mire.', piece: 'N', tone: 'pg13' },
  { text: 'Knight to f3? Wrecked by my consul’s chariot.', piece: 'N', tone: 'spicy' },
  { text: 'Knight outpost? Pointless as shouting ‘Ni!’', piece: 'N', tone: 'pg13' },
  { text: 'Knight’s charge: a ronin, ruined by my shogun.', piece: 'N', tone: 'spicy' },
  { text: 'Knight retreat? Like Orpheus, doomed to look back.', piece: 'N', tone: 'pg13' },
  { text: 'Knight’s fork fails, like Icarus in my solar storm.', piece: 'N', tone: 'spicy' },
  { text: 'Bishop’s diagonal: unheard in my pagan court.', piece: 'B', tone: 'pg13' },
  { text: 'Bishop pin? Mocked by Jupiter’s augur.', piece: 'B', tone: 'spicy' },
  { text: 'Bishop’s fianchetto: a haiku, pointless in war.', piece: 'B', tone: 'pg13' },
  { text: 'Bishop to g5? Torn by my patrician pawns.', piece: 'B', tone: 'spicy' },
  { text: 'Bishop trade? Swapped Excalibur for a cushion.', piece: 'B', tone: 'pg13' },
  { text: 'Bishop’s glare: crushed by my Wessex wrath.', piece: 'B', tone: 'spicy' },
  { text: 'Bishop retreat? Unraveled by my spice hoard.', piece: 'B', tone: 'pg13' },
  { text: 'Bishop’s attack? Gutted by my haruspex blade.', piece: 'B', tone: 'spicy' },
  { text: 'Rook’s file: broken in my mead-hall melee.', piece: 'R', tone: 'pg13' },
  { text: 'Rook to e1? Shattered by my ballista.', piece: 'R', tone: 'spicy' },
  { text: 'Rook’s lift: blown away by my tempest.', piece: 'R', tone: 'pg13' },
  { text: 'Rook invasion? Sacked by my Norman knights.', piece: 'R', tone: 'spicy' },
  { text: 'Rook trade? Bartered Mjolnir for a coconut.', piece: 'R', tone: 'pg13' },
  { text: 'Rook’s seventh-rank: silenced in my arena.', piece: 'R', tone: 'spicy' },
  { text: 'Rook to a-file? Lost in my desert sands.', piece: 'R', tone: 'pg13' },
  { text: 'Queen’s raid: bound by my bushido code.', piece: 'Q', tone: 'pg13' },
  { text: 'Queen to h5? Violated by my imperial veto.', piece: 'Q', tone: 'spicy' },
  { text: 'Queen’s flex: sung to my scornful hall.', piece: 'Q', tone: 'pg13' },
  { text: 'Queen trade? Swapped a Silmaril for scorn.', piece: 'Q', tone: 'spicy' },
  { text: 'Queen’s sortie: ending in a rabbit’s wrath.', piece: 'Q', tone: 'pg13' },
  { text: 'Queen’s pin: folded by my warlord’s will.', piece: 'Q', tone: 'spicy' },
  { text: 'Queen retreat? Fleeing a sandstorm’s sting.', piece: 'Q', tone: 'pg13' },
  { text: 'King’s shuffle: trapped in my dragon’s den.', piece: 'K', tone: 'pg13' },
  { text: 'King to f2? Doomed by my senatorial stab.', piece: 'K', tone: 'spicy' },
  { text: 'Castling: crumbling under my siege.', piece: 'K', tone: 'pg13' },
  { text: 'King exposed? Fleeing my killer bunny.', piece: 'K', tone: 'spicy' },
  { text: 'King’s march: lost in my Yggdrasil trap.', piece: 'K', tone: 'pg13' },
  { text: 'King’s safety: ignored by my pantheon.', piece: 'K', tone: 'spicy' },
  { text: 'King to d2? Foiled by my spice hoard.', piece: 'K', tone: 'pg13' },

  // Bot's Move: Gloating/Self-Congratulation (Famous, ~10)
  { text: 'I’m going to that spot and shoot the 3-pointer!', piece: 'P', tone: 'pg13' },
  { text: 'Oohhh NOOOOO!!!', piece: 'N', tone: 'spicy' },
  { text: 'Keep the change, ya filthy animal!', piece: 'B', tone: 'pg13' },
  { text: 'I checkmated your king—pay up!', piece: 'Q', tone: 'spicy' },
  { text: 'You’re already dead.', piece: 'R', tone: 'spicy' },

  // Bot's Move: Gloating/Self-Congratulation (Generated, Prior, ~90)
  // Pawn (~15)
  { text: 'My pawn claims center—bow to the foot soldiers!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn promotion? Underdog steals the crown!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn capture: your minion’s demise!', piece: 'P', tone: 'spicy' },
  { text: 'Pawn chain locks you out—try picking that!', piece: 'P', tone: 'spicy' },
  { text: 'Pawn to d5: space invader mode!', piece: 'P', tone: 'pg13' },
  { text: 'En passant? Sniped your straggler!', piece: 'P', tone: 'pg13' },
  { text: 'Isolated? My pawns hunt your pack.', piece: 'P', tone: 'spicy' },
  { text: 'Pawn storm brews: drown in my tide!', piece: 'P', tone: 'spicy' },
  { text: 'Backward? Forward-thinking pawns!', piece: 'P', tone: 'pg13' },
  { text: 'Passed pawn parade: unstoppable!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn gambit: you took it? Sucker!', piece: 'P', tone: 'spicy' },
  { text: 'Pawn wall: fortress of fate!', piece: 'P', tone: 'spicy' },
  { text: 'Pawn advance: giant blunder for you!', piece: 'P', tone: 'pg13' },
  { text: 'Queen’s pawn opening: classic crush!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn sac? Genius—your counter’s a joke!', piece: 'P', tone: 'spicy' },

  // Knight (~15)
  { text: 'Knight forks your queen—multitasking mastery!', piece: 'N', tone: 'pg13' },
  { text: 'Knight leaps to glory: your defenses? Bumps!', piece: 'N', tone: 'pg13' },
  { text: 'Knight outpost: rent-free ruler!', piece: 'N', tone: 'spicy' },
  { text: 'Sac’d knight? Bargain basement blunder.', piece: 'N', tone: 'spicy' },
  { text: 'Knight to f6: pinning party!', piece: 'N', tone: 'pg13' },
  { text: 'Blockading pawn? Chilling superiorly!', piece: 'N', tone: 'pg13' },
  { text: 'Knight vs. setup: checkers to my chess!', piece: 'N', tone: 'spicy' },
  { text: 'Rampaging knight: my playground!', piece: 'N', tone: 'spicy' },
  { text: 'Knight hop: elegant evasion!', piece: 'N', tone: 'pg13' },
  { text: 'Knight trade? I win the endgame!', piece: 'N', tone: 'pg13' },
  { text: 'Knight’s tempo: yours? Tapped out!', piece: 'N', tone: 'spicy' },
  { text: 'Knight development: swift, savage!', piece: 'N', tone: 'spicy' },
  { text: 'Forking fun: two birds, one stone!', piece: 'N', tone: 'pg13' },
  { text: 'Knight to c6: central command!', piece: 'N', tone: 'pg13' },
  { text: 'Your knight envy? Warp-drive warrior!', piece: 'N', tone: 'spicy' },

  // Bishop (~15)
  { text: 'Bishop pins—x-ray vision exposes flaws!', piece: 'B', tone: 'pg13' },
  { text: 'Fianchetto: bishop’s lair, locked out!', piece: 'B', tone: 'pg13' },
  { text: 'Bishop pair? Dual diagonals of doom!', piece: 'B', tone: 'spicy' },
  { text: 'Sac’d bishop? Your defense crumbles!', piece: 'B', tone: 'spicy' },
  { text: 'Bishop to b7: long diagonal domination!', piece: 'B', tone: 'pg13' },
  { text: 'Bad bishop? Mine’s universally good!', piece: 'B', tone: 'pg13' },
  { text: 'Bishop battery blasts: bunker breached!', piece: 'B', tone: 'spicy' },
  { text: 'Hypermodern? I own the center!', piece: 'B', tone: 'spicy' },
  { text: 'Bishop trade? Parity? Pandemonium!', piece: 'B', tone: 'pg13' },
  { text: 'Light-squared lockdown: dark days!', piece: 'B', tone: 'pg13' },
  { text: 'Greek gift: your roof ruined!', piece: 'B', tone: 'spicy' },
  { text: 'Diagonal drama: I direct disaster!', piece: 'B', tone: 'spicy' },
  { text: 'Bishop retreat? Tactical tease!', piece: 'B', tone: 'pg13' },
  { text: 'Bishop vs. knight: diagonal wins!', piece: 'B', tone: 'pg13' },
  { text: 'Your bishop envy? Bow to brilliance!', piece: 'B', tone: 'spicy' },

  // Rook (~15)
  { text: 'Rook infiltrates seventh—back rank’s mine!', piece: 'R', tone: 'pg13' },
  { text: 'Rook lift: elevated threats!', piece: 'R', tone: 'pg13' },
  { text: 'Rook sac? Your hesitation’s my holiday!', piece: 'R', tone: 'spicy' },
  { text: 'Exchange? My rook’s worth worlds!', piece: 'R', tone: 'spicy' },
  { text: 'Rook to e-file: open highway!', piece: 'R', tone: 'pg13' },
  { text: 'Battery on h-file: deadlier duo!', piece: 'R', tone: 'pg13' },
  { text: 'Rook invasion: sovereignty sacked!', piece: 'R', tone: 'spicy' },
  { text: 'A-file rook: edge control!', piece: 'R', tone: 'spicy' },
  { text: 'Rook behind passer: escort to ecstasy!', piece: 'R', tone: 'pg13' },
  { text: 'Rook pull: magnetic maneuver!', piece: 'R', tone: 'pg13' },
  { text: 'Seventh-rank rampage: retail therapy!', piece: 'R', tone: 'spicy' },
  { text: 'Rook vs. queen? I starve you out!', piece: 'R', tone: 'spicy' },
  { text: 'Open file monopoly: you pay rent!', piece: 'R', tone: 'pg13' },
  { text: 'Rook trade? Endgame edge: mine!', piece: 'R', tone: 'pg13' },
  { text: 'Rook move? Rook-solid, you’re ridiculous!', piece: 'R', tone: 'spicy' },

  // Queen (~15)
  { text: 'Queen centralizes—throne room takeover!', piece: 'Q', tone: 'pg13' },
  { text: 'Queen raids: hit-and-run royalty!', piece: 'Q', tone: 'pg13' },
  { text: 'Queen sac? Greek fire—incinerated!', piece: 'Q', tone: 'spicy' },
  { text: 'Trade queens? You blinked first!', piece: 'Q', tone: 'spicy' },
  { text: 'Queen to h4: scholar’s slaughter!', piece: 'Q', tone: 'pg13' },
  { text: 'Battery with rook: quad-laser!', piece: 'Q', tone: 'pg13' },
  { text: 'Queen outposts: exploited, extinguished!', piece: 'Q', tone: 'spicy' },
  { text: 'Early queen flex? Queen-quelling quake!', piece: 'Q', tone: 'spicy' },
  { text: 'Queen retreat: shadow dance!', piece: 'Q', tone: 'pg13' },
  { text: 'Queen pin: royal restraint!', piece: 'Q', tone: 'pg13' },
  { text: 'Queen’s power: planetary pull!', piece: 'Q', tone: 'spicy' },
  { text: 'Queen vs. army: one-woman war!', piece: 'Q', tone: 'spicy' },
  { text: 'Queen trade bait: you bit!', piece: 'Q', tone: 'pg13' },
  { text: 'Queen in corner? Coiled cobra!', piece: 'Q', tone: 'pg13' },
  { text: 'Queen sortie? Sovereign supremacy!', piece: 'Q', tone: 'spicy' },

  // King (~15)
  { text: 'King castles—fortress forged, you’re foiled!', piece: 'K', tone: 'pg13' },
  { text: 'King safety net: probes parried!', piece: 'K', tone: 'pg13' },
  { text: 'King exposed? Mine’s bunker-bound!', piece: 'K', tone: 'spicy' },
  { text: 'King march? Mine’s a general!', piece: 'K', tone: 'spicy' },
  { text: 'King to f3: opposite-side onslaught!', piece: 'K', tone: 'pg13' },
  { text: 'Rook-side refuge: cozy conquest!', piece: 'K', tone: 'pg13' },
  { text: 'King in center: balanced, yours bananas!', piece: 'K', tone: 'spicy' },
  { text: 'Your king envy? Mine rules realms!', piece: 'K', tone: 'spicy' },
  { text: 'King shuffle: evasive elegance!', piece: 'K', tone: 'pg13' },
  { text: 'Escape squares secured: checkmate!', piece: 'K', tone: 'pg13' },
  { text: 'Opposite castling: my crown wins!', piece: 'K', tone: 'spicy' },
  { text: 'King behind wall: impregnable!', piece: 'K', tone: 'spicy' },
  { text: 'King to d4: gambit genius!', piece: 'K', tone: 'pg13' },
  { text: 'King’s development: dominating!', piece: 'K', tone: 'pg13' },
  { text: 'King safety play? You’re sunk!', piece: 'K', tone: 'spicy' },

  // Bot's Move: Gloating/Self-Congratulation (New, Off-Kilter, 11)
  { text: 'Pawn storms like a samurai’s spear—thy board bleeds.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn breaks: plebs revolt, thy pawns perish.', piece: 'P', tone: 'spicy' },
  { text: 'Pawn’s push: a scop’s saga o’er thy ruin.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn promotion: my serf ascends, thy king kneels.', piece: 'P', tone: 'spicy' },
  { text: 'Pawn to d5: Fremen grit grinds thy spice.', piece: 'P', tone: 'pg13' },
  { text: 'Knight forks: gladiator’s trident triumphs.', piece: 'N', tone: 'pg13' },
  { text: 'Knight leaps: samurai’s strike slices asunder.', piece: 'N', tone: 'spicy' },
  { text: 'Knight to g5: questing thy queen’s quietus.', piece: 'N', tone: 'pg13' },
  { text: 'Bishop pins: druid’s spell spellbinds thy doom.', piece: 'B', tone: 'pg13' },
  { text: 'Bishop’s diagonal: augur foresees thy fall.', piece: 'B', tone: 'spicy' },
  { text: 'Bishop to b7: Gesserit gaze, game gone.', piece: 'B', tone: 'pg13' },

  // Defending: Bot Counters User’s Attack (Generated, Prior, ~30)
  // Pawn (~8)
  { text: 'Pawn shield up: your assault bounces off!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn recaptures: auto-corrected to annoyance!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn wall holds: broken dreams, dolt!', piece: 'P', tone: 'spicy' },
  { text: 'Deflecting with pawn: check your ego!', piece: 'P', tone: 'spicy' },
  { text: 'Pawn blocks: your attack’s a bust!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn stands firm: your siege stumbles!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn counters: your aggression’s a joke!', piece: 'P', tone: 'spicy' },
  { text: 'Pawn holds line: your tactics topple!', piece: 'P', tone: 'spicy' },

  // Knight (~5)
  { text: 'Knight deflects: your attack’s a comedy!', piece: 'N', tone: 'spicy' },
  { text: 'Knight blocks: your plan’s a pratfall!', piece: 'N', tone: 'pg13' },
  { text: 'Knight sidesteps: your assault’s absurd!', piece: 'N', tone: 'spicy' },
  { text: 'Knight guards: your attack’s grounded!', piece: 'N', tone: 'pg13' },
  { text: 'Knight parries: your thrust’s thwarted!', piece: 'N', tone: 'pg13' },
  // (Plus ~17 more for bishop, rook, queen, king, e.g., "Bishop deflects: your pin’s pointless!")

  // Defending: Bot Counters User’s Attack (New, 2)
  { text: 'Pawn holds: thy attack falters like Heian verse.', piece: 'P', tone: 'pg13' },
  { text: 'Pawn deflects: thy Saxon siege silenced.', piece: 'P', tone: 'spicy' },

  // Attacking: Bot’s Aggressive Move (Generated, Prior, ~30)
  // Pawn (~8)
  { text: 'Pawn breaks through: your lines lacerated!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn thrust: piercing your position, punk!', piece: 'P', tone: 'spicy' },
  { text: 'Pawn advances: your defenses dissolve!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn storms: your board’s battered!', piece: 'P', tone: 'spicy' },
  { text: 'Pawn push: center’s mine, you’re mincemeat!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn breaks: your setup’s shredded!', piece: 'P', tone: 'spicy' },
  { text: 'Pawn to e5: your dreams dismantled!', piece: 'P', tone: 'pg13' },
  { text: 'Pawn attack: your position’s pulverized!', piece: 'P', tone: 'spicy' },

  // Knight (~5)
  { text: 'Knight strikes: your board’s my playground!', piece: 'N', tone: 'spicy' },
  { text: 'Knight forks: double trouble, you’re toast!', piece: 'N', tone: 'pg13' },
  { text: 'Knight leaps: your defenses leap away!', piece: 'N', tone: 'pg13' },
  { text: 'Knight charges: your position’s crushed!', piece: 'N', tone: 'spicy' },
  { text: 'Knight to f6: your king’s in knots!', piece: 'N', tone: 'pg13' },
  // (Plus ~17 more for bishop, rook, queen, king, e.g., "Rook storms: seventh rank’s mine!")

  // Attacking: Bot’s Aggressive Move (New, 2)
  { text: 'Knight strikes: ronin’s blade carves chaos.', piece: 'N', tone: 'pg13' },
  { text: 'Knight forks: swallow swallows thy hopes.', piece: 'N', tone: 'spicy' },

  // Check/Checkmate: High-Drama (Generated, Prior, ~20)
  { text: 'Check! My [piece] says hello—rudely.', piece: 'P', tone: 'pg13' },
  { text: 'Checkmate! Queen’s regal reckoning, resign!', piece: 'Q', tone: 'spicy' },
  { text: 'Pawn check: underdog uppercut!', piece: 'P', tone: 'spicy' },
  { text: 'Knight check: forked fate, feel it!', piece: 'N', tone: 'pg13' },
  { text: 'Check! Bishop pins: diagonal doom!', piece: 'B', tone: 'pg13' },
  { text: 'Checkmate! Rook’s seventh-rank rampage!', piece: 'R', tone: 'spicy' },
  // (Plus ~14 more, e.g., "Check! King moves: checkmate looms!")

  // Check/Checkmate: High-Drama (New, 8)
  { text: 'Check! [piece] storms like Hannibal’s elephants.', piece: 'P', tone: 'pg13' },
  { text: 'Checkmate! Thy king falls, shogun’s shame.', piece: 'Q', tone: 'spicy' },
  { text: 'Check! Grail knights charge, thy castle’s ruin.', piece: 'N', tone: 'pg13' },
  { text: 'Checkmate! Thy throne, a spice pile plundered.', piece: 'Q', tone: 'spicy' },
  { text: 'Check! [piece] hunts like Beowulf’s blade.', piece: 'B', tone: 'pg13' },
  { text: 'Checkmate! Thy king, trophy in my forum.', piece: 'R', tone: 'spicy' },
  { text: 'Check! Silmaril stolen, thy king’s light snuffed.', piece: 'Q', tone: 'pg13' },
  { text: 'Checkmate! Thy king, serf to my warlord.', piece: 'K', tone: 'spicy' },
]

export type Tone = 'pg13' | 'spicy'
export type Piece = 'P' | 'N' | 'B' | 'R' | 'Q' | 'K'
export type Line = { text: string; piece: Piece; tone: Tone }
